[SPOT_1H]
symbol="ETHUSDT"
start_time="2020-01-01"
end_time="2023-01-01"
active="SPOT"
interval="1h"

[FUTURES_1H]
symbol="ETHUSDT"
start_time="2020-01-01"
end_time="2023-01-01"
active="FUTURES"
interval="1h"

[SPOT_5M]
symbol="ETHUSDT"
start_time="2020-01-01"
end_time="2023-01-01"
active="SPOT"
interval="5m"

[FUTURES_5M]
symbol="ETHUSDT"
start_time="2020-01-01"
end_time="2023-01-01"
active="FUTURES"
interval="5m"

[FUNDRATES]
symbol="ETHUSDT"
start_time="2020-01-01"
end_time="2023-01-01"
active="FUNDRATES"